rm zipp-3.15.0.dist-info -rf
rm zipp -rf
rm wrapt -rf
rm tensorboard_plugin_wit-1.8.1.dist-info -rf
rm tensorboard_plugin_wit -rf
rm pyasn1-0.4.8.dist-info -rf
rm pyasn1 -rf
rm libclang-16.0.0.dist-info -rf
rm flatbuffers-23.3.3.dist-info -rf
rm flatbuffers -rf
rm clang -rf
rm wrapt-1.14.1.dist-info -rf
rm wheel-0.40.0.dist-info -rf
rm wheel -rf
rm urllib3-1.26.15.dist-info -rf
rm urllib3 -rf
rm typing_extensions.py -rf
rm typing_extensions-4.5.0.dist-info -rf
rm termcolor-2.2.0.dist-info -rf
rm termcolor -rf
rm tensorflow_io_gcs_filesystem-0.31.0.dist-info -rf
rm tensorflow_io_gcs_filesystem -rf
rm tensorflow_estimator-2.12.0.dist-info -rf
rm tensorflow_estimator -rf
rm tensorboard_data_server-0.7.0.dist-info -rf
rm tensorboard_data_server -rf
rm six.py -rf
rm six-1.16.0.dist-info -rf
rm setuptools -rf
rm __pycache__ -rf
rm pkg_resources -rf
rm distutils-precedence.pth -rf
rm _distutils_hack -rf
rm setuptools-67.6.0.dist-info -rf
rm rsa-4.9.dist-info -rf
rm rsa -rf
rm pyasn1_modules-0.2.8.dist-info -rf
rm pyasn1_modules -rf
rm protobuf-4.22.1.dist-info -rf
rm packaging-23.0.dist-info -rf
rm packaging -rf
rm oauthlib -rf
rm oauthlib-3.2.2.dist-info -rf
rm numpy.libs -rf
rm numpy -rf
rm numpy-1.23.5.dist-info -rf
rm MarkupSafe-2.1.2.dist-info -rf
rm markupsafe -rf
rm keras -rf
rm keras-2.12.0.dist-info -rf
rm idna-3.4.dist-info -rf
rm idna -rf
rm grpcio-1.51.3.dist-info -rf
rm grpc -rf
rm gast -rf
rm Werkzeug-2.2.3.dist-info -rf
rm werkzeug -rf
rm gast-0.4.0.dist-info -rf
rm charset_normalizer-3.1.0.dist-info -rf
rm charset_normalizer -rf
rm certifi-2022.12.7.dist-info -rf
rm certifi -rf
rm cachetools-5.3.0.dist-info -rf
rm cachetools -rf
rm absl_py-1.4.0.dist-info -rf
rm absl -rf
rm scipy.libs -rf
rm scipy -rf
rm scipy-1.10.1.dist-info -rf
rm requests-2.28.2.dist-info -rf
rm requests -rf
rm opt_einsum-3.3.0.dist-info -rf
rm opt_einsum -rf
rm requests_oauthlib-1.3.1.dist-info -rf
rm requests_oauthlib -rf
rm pasta -rf
rm markdown -rf
rm importlib_metadata-6.1.0.dist-info -rf
rm importlib_metadata -rf
rm h5py.libs -rf
rm h5py-3.8.0.dist-info -rf
rm h5py -rf
rm google_pasta-0.2.0.dist-info -rf
rm google_auth-2.16.3-py3.9-nspkg.pth -rf
rm google_auth-2.16.3.dist-info -rf
rm google -rf
rm astunparse-1.6.3.dist-info -rf
rm astunparse -rf
rm Markdown-3.4.3.dist-info -rf
rm jax -rf
rm jax-0.4.6-py3.9.egg-info -rf
rm google_auth_oauthlib-0.4.6.dist-info -rf
rm google_auth_oauthlib -rf
rm tensorboard-2.12.0.dist-info -rf
rm tensorboard -rf
rm tensorflow -rf
rm tensorflow-2.12.0.dist-info -rf
rm bin -rf